import { routing } from '@/../i18n/routing';
import { hreflangFor } from '@/lib/i18n/locales';

// The sitemap is split across an index and one child per content type, mirroring
// what the crawlers of large sites expect:
//
//   /sitemap_index.xml -> /page-sitemap.xml, /legal-sitemap.xml
//
// Splitting by type rather than by locale keeps every language variant of a page
// — and therefore its whole hreflang cluster — inside a single file. A new
// section (tournaments, gallery) becomes another entry in SITEMAPS and another
// route handler, without touching the existing children.
//
// All three documents are generated by route handlers under src/app/, so there
// is nothing to regenerate by hand and nothing committed that can drift.

// Hard-coded rather than read from NEXT_PUBLIC_SITE_URL, unlike robots.ts.
// These routes are `force-static`, so whatever the origin resolves to at BUILD
// time is baked into the published XML — and a developer build picks up
// .env.local, which points at localhost. Production only gets the right answer
// because its image happens not to carry that file; that is luck, not a design.
// A sitemap full of localhost URLs submitted to Search Console is a far worse
// failure than a staging deploy advertising the production origin, so the value
// is fixed here. sitemap.test.ts holds the line.
export const SITE_URL = 'https://clutchzone.club';

export type PageEntry = { path: string; lastModified: string };

// Google only uses <lastmod> when it is "consistently and verifiably accurate",
// so it has to be the date of the last significant change to the page's content
// — not the moment the sitemap happened to be generated. Bump a date by hand
// when the main content, structured data or links of that page actually change;
// a dependency bump does not count.
//
// Check the page's *content*, not its route folder. The legal text lives in
// src/content/legal/{terms,privacy}.<locale>.ts and the home page's copy in
// src/components/sections/ — editing the route's page.tsx is usually plumbing,
// and dating from it reports the content as older than it is.
export const SITEMAPS = {
  page: [
    { path: '', lastModified: '2026-09-14' },
    { path: '/rezervace', lastModified: '2026-09-03' },
    { path: '/kredit', lastModified: '2026-09-03' },
  ],
  legal: [
    { path: '/terms', lastModified: '2026-09-04' },
    { path: '/privacy', lastModified: '2026-09-04' },
    { path: '/cookies', lastModified: '2026-09-04' },
  ],
} satisfies Record<string, PageEntry[]>;

export type SitemapName = keyof typeof SITEMAPS;

export const SITEMAP_NAMES = Object.keys(SITEMAPS) as SitemapName[];

/** Public path of a child sitemap, e.g. `page` -> `/page-sitemap.xml`. */
export function sitemapPath(name: SitemapName): string {
  return `/${name}-sitemap.xml`;
}

// The protocol requires every tag value to be entity escaped. None of today's
// paths contain a reserved character, but a future slug with an `&` in it would
// otherwise produce a document no parser accepts.
function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function urlFor(locale: string, path: string): string {
  return escapeXml(`${SITE_URL}/${locale}${path}`);
}

// sitemap.xsd declares tUrl as a strict xsd:sequence — loc, lastmod, changefreq,
// priority, and only then `xsd:any namespace="##other"`. Foreign-namespace
// extensions such as <xhtml:link> therefore belong at the END of the block.
// Next's own sitemap serializer emits them straight after <loc>, which makes
// every <lastmod> that follows "not expected" under the schema; that is exactly
// why this file builds the XML itself instead of using the app/sitemap.ts
// convention. sitemap.test.ts guards the ordering.
//
// <changefreq> and <priority> are omitted on purpose: Google ignores both.
function urlBlock(locale: string, { path, lastModified }: PageEntry): string {
  const alternates = [
    ...routing.locales.map(
      (l) => `<xhtml:link rel="alternate" hreflang="${hreflangFor(l)}" href="${urlFor(l, path)}"/>`,
    ),
    `<xhtml:link rel="alternate" hreflang="x-default" href="${urlFor(routing.defaultLocale, path)}"/>`,
  ];

  return [
    '<url>',
    `<loc>${urlFor(locale, path)}</loc>`,
    `<lastmod>${lastModified}</lastmod>`,
    ...alternates,
    '</url>',
  ].join('\n');
}

export function buildUrlsetXml(name: SitemapName): string {
  // Page-major rather than locale-major: the language variants of one page sit
  // next to each other, which is how you read the file when checking hreflang.
  const urls = SITEMAPS[name].flatMap((entry) =>
    routing.locales.map((locale) => urlBlock(locale, entry)),
  );

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    ...urls,
    '</urlset>',
    '',
  ].join('\n');
}

export function buildSitemapIndexXml(): string {
  const entries = SITEMAP_NAMES.map((name) => {
    // Derived, never hand-written: a child's <lastmod> is the newest date it
    // actually contains, so adding a page keeps the index honest by itself.
    const lastModified = SITEMAPS[name]
      .map((entry) => entry.lastModified)
      .reduce((newest, date) => (date > newest ? date : newest));

    return [
      '<sitemap>',
      `<loc>${escapeXml(`${SITE_URL}${sitemapPath(name)}`)}</loc>`,
      `<lastmod>${lastModified}</lastmod>`,
      '</sitemap>',
    ].join('\n');
  });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries,
    '</sitemapindex>',
    '',
  ].join('\n');
}
